FROM ekidd/rust-musl-builder:latest AS builder
WORKDIR /home/rust/src
ADD --chown=rust:rust . ./
RUN sudo apt update && sudo apt install -y libluajit-5.1-dev libpcap-dev \
 && cargo build --release


FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder \
    /home/rust/src/target/x86_64-unknown-linux-musl/release/hepagent \
    /home/rust/src/scripts /scripts \
    /usr/local/bin/
CMD /usr/local/bin/hepagent

